### ISSUE TITLE
有报错 Error 1054: Unknown column 'GENERATION_EXPRESSION' in 'field list'

### ISSUE THREAD

**Issue by 54huige** [camry/go-mysqldiff#1]
是不是和数据库版本有关系 我是5.6的mysql
Error 1054: Unknown column 'GENERATION_EXPRESSION' in 'field list'

**Comment by camry** [comment]
这个目前是从 5.7 开始支持，我这边兼容下。

**Comment by 54huige** [comment]
感谢大佬 ，我想在这基础上扩展 支持 数据同步 还有 可以自定义配置部分表的部分字段值更新。我之前也就想写这个软件，一直没找到golang版本的  当时我还想能加入lua接管部分数据处理 感觉更灵活些 有的数据可能还要自己根据正则或其他判断做特殊处理 再生成sql语句并自动执行 在记录执行失败的sql方便再处理

**Comment by camry** [comment]
fixed [https://github.com/camry/go-mysqldiff/commit/69a6f1abe2318547184c30931370cbe01dac3af3](https://github.com/camry/go-mysqldiff/commit/69a6f1abe2318547184c30931370cbe01dac3af3)
