### ISSUE TITLE
生成Modify字段的时候能不能做成一条SQL更新一个字段。

### ISSUE THREAD

**Issue by kldcty** [camry/go-mysqldiff#4]
在TIDB中一次只能更新一个字段，这样做为了兼容TIDB。

**Comment by camry** [comment]
@freshtech2021 感谢你的建议，TiDB 还没有测试验证过，后续会考虑。

**Comment by camry** [comment]
@freshtech2021 v3.0.6 版本，ALTER TABLE 已支持 TiDB。
