### ISSUE TITLE
bug 反馈

### ISSUE THREAD

**Issue by lianhuazi** [camry/go-mysqldiff#5]
兄弟你好。你得开源软件很不错，希望能继续维护。感激不尽
但是很不幸，有几个bug

我测试得方法
```bash
./mysqldiff -c -d worker_db_831321:test -s root:123456@172.17.0.1:3306 -t root:123456@172.17.0.1:3306 >ff.sql
```

```bash
lianhuazi@lianhuazi-PC:~/go-mysqldiff$ mysql -uroot -h172.17.0.1 -p123456 test<ff.sql
ERROR 1064 (42000) at line 7365: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-00-00 00:00:00 COMMENT '',
  PRIMARY KEY (`id`),
```

1  丢失引号
发现结构生成丢失数据 导致sql 导入 错误，我做比较。发现是少了一对引号  去源结构查看是存在
源：

比对得到sql：

2 和Navicat 工具得结构对比。有丢失结构得情况
为了检查准确 我通过navicat 得结构同步做了对比。发现还有很多结构丢失

**Comment by lianhuazi** [comment]
兄弟更新了。
```bash
go-mysqldiff-master ./mysqldiff -c -d worker_db_831321:test1 -s root:123456@172.17.0.1:3306 -t root:123456@172.17.0.1:3306 >ff.sql
```
```bash
go-mysqldiff-master mysql -h 172.17.0.1 -uroot -p123456 test1 < ff.sql
ERROR 1064 (42000) at line 7365: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-00-00 00:00:00 COMMENT '',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`)
) ' at line 9
```
```bash
 go-mysqldiff-master ./mysqldiff -v
```

mysqldiff version v3.0.4

这个问题还是存在 更新后还是差引号

反馈不能上放图片？

**Comment by camry** [comment]
把生成的sql文件发我看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "camry/go-mysqldiff"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月7日(星期五) 下午2:58
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [camry/go-mysqldiff] bug 反馈 (Issue #5)





 
兄弟更新了。
 
➜  go-mysqldiff-master ./mysqldiff -c -d worker_db_831321:test1 -s ***@***.***:3306 -t ***@***.***:3306 &gt;ff.sql
 ➜  go-mysqldiff-master mysql -h 172.17.0.1 -uroot -p123456 test1 < ff.sql
 ERROR 1064 (42000) at line 7365: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-00-00 00:00:00 COMMENT '',
 PRIMARY KEY (id),
 KEY user_id (user_id)
 ) ' at line 9
 ➜  go-mysqldiff-master
 
这个问题还是存在
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lianhuazi** [comment]
不能上传吧。我发邮箱附件给你

**Comment by camry** [comment]
您好，已发布 v3.0.5 版本，可以再看看。

**Comment by lianhuazi** [comment]
> 您好，已发布 v3.0.5 版本，可以再看看。

好得。大佬兄弟

**Comment by lianhuazi** [comment]
大兄弟威武，引号问题修复了。
但是还存在丢数据，情况
我用Navicat 比对结果发现
源：
```sql
CREATE TABLE `worker_db_831321`.`attachment`  (
  `id` int(11) NOT NULL,
  `pos_id` int(11) NOT NULL,
  `module` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `path` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `model` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `attribute` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `pk` int(11) NOT NULL,
  `create_time` int(11) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_pos_id`(`pos_id`) USING BTREE,
  INDEX `idx_module`(`module`) USING BTREE,
  INDEX `idx_model`(`model`) USING BTREE,
  INDEX `idx_attribute`(`attribute`) USING BTREE,
  INDEX `idx_map`(`model`, `attribute`, `pk`) USING BTREE,
  CONSTRAINT `pos_id` FOREIGN KEY (`pos_id`) REFERENCES `worker_db_831321`.`attachment_position` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;
```

目标：
```sql
CREATE TABLE `test1`.`attachment`  (
  `id` int(11) NOT NULL,
  `pos_id` int(11) NOT NULL,
  `module` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `path` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `model` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `attribute` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `pk` int(11) NOT NULL,
  `create_time` int(11) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_pos_id`(`pos_id`) USING BTREE,
  INDEX `idx_module`(`module`) USING BTREE,
  INDEX `idx_model`(`model`) USING BTREE,
  INDEX `idx_attribute`(`attribute`) USING BTREE,
  INDEX `idx_map`(`model`, `attribute`, `pk`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;
```

丢失：  
```sql
CONSTRAINT `pos_id` FOREIGN KEY (`pos_id`) REFERENCES `worker_db_831321`.`attachment_position` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
```

**Comment by camry** [comment]
> 大兄弟威武，引号问题修复了。 但是还存在丢数据，情况 我用Navicat 比对结果发现 源：
> 
> ```sql
> CREATE TABLE `worker_db_831321`.`attachment`  (
>   `id` int(11) NOT NULL,
>   `pos_id` int(11) NOT NULL,
>   `module` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
>   `path` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
>   `model` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
>   `attribute` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
>   `pk` int(11) NOT NULL,
>   `create_time` int(11) NOT NULL,
>   PRIMARY KEY (`id`) USING BTREE,
>   INDEX `idx_pos_id`(`pos_id`) USING BTREE,
>   INDEX `idx_module`(`module`) USING BTREE,
>   INDEX `idx_model`(`model`) USING BTREE,
>   INDEX `idx_attribute`(`attribute`) USING BTREE,
>   INDEX `idx_map`(`model`, `attribute`, `pk`) USING BTREE,
>   CONSTRAINT `pos_id` FOREIGN KEY (`pos_id`) REFERENCES `worker_db_831321`.`attachment_position` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
> ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;
> ```
> 
> 目标：
> 
> ```sql
> CREATE TABLE `test1`.`attachment`  (
>   `id` int(11) NOT NULL,
>   `pos_id` int(11) NOT NULL,
>   `module` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
>   `path` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
>   `model` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
>   `attribute` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
>   `pk` int(11) NOT NULL,
>   `create_time` int(11) NOT NULL,
>   PRIMARY KEY (`id`) USING BTREE,
>   INDEX `idx_pos_id`(`pos_id`) USING BTREE,
>   INDEX `idx_module`(`module`) USING BTREE,
>   INDEX `idx_model`(`model`) USING BTREE,
>   INDEX `idx_attribute`(`attribute`) USING BTREE,
>   INDEX `idx_map`(`model`, `attribute`, `pk`) USING BTREE
> ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;
> ```
> 
> 丢失：
> 
> ```sql
> CONSTRAINT `pos_id` FOREIGN KEY (`pos_id`) REFERENCES `worker_db_831321`.`attachment_position` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
> ```

竟然用到外键了，笑哭...
这个我得抽空研究下，暂时还没法快速更新。

这个 mysqldiff 工具，也是我们游戏项目发版本时，诞生的，还有些功能不完善，敬请谅解！

**Comment by lianhuazi** [comment]
> > 大兄弟威武，引号问题修复了。 但是还存在丢数据，情况 我用Navicat 比对结果发现 源：
> > ```sql
> > CREATE TABLE `worker_db_831321`.`attachment`  (
> >   `id` int(11) NOT NULL,
> >   `pos_id` int(11) NOT NULL,
> >   `module` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
> >   `path` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
> >   `model` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
> >   `attribute` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
> >   `pk` int(11) NOT NULL,
> >   `create_time` int(11) NOT NULL,
> >   PRIMARY KEY (`id`) USING BTREE,
> >   INDEX `idx_pos_id`(`pos_id`) USING BTREE,
> >   INDEX `idx_module`(`module`) USING BTREE,
> >   INDEX `idx_model`(`model`) USING BTREE,
> >   INDEX `idx_attribute`(`attribute`) USING BTREE,
> >   INDEX `idx_map`(`model`, `attribute`, `pk`) USING BTREE,
> >   CONSTRAINT `pos_id` FOREIGN KEY (`pos_id`) REFERENCES `worker_db_831321`.`attachment_position` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
> > ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 目标：
> > ```sql
> > CREATE TABLE `test1`.`attachment`  (
> >   `id` int(11) NOT NULL,
> >   `pos_id` int(11) NOT NULL,
> >   `module` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
> >   `path` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
> >   `model` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
> >   `attribute` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
> >   `pk` int(11) NOT NULL,
> >   `create_time` int(11) NOT NULL,
> >   PRIMARY KEY (`id`) USING BTREE,
> >   INDEX `idx_pos_id`(`pos_id`) USING BTREE,
> >   INDEX `idx_module`(`module`) USING BTREE,
> >   INDEX `idx_model`(`model`) USING BTREE,
> >   INDEX `idx_attribute`(`attribute`) USING BTREE,
> >   INDEX `idx_map`(`model`, `attribute`, `pk`) USING BTREE
> > ) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 丢失：
> > ```sql
> > CONSTRAINT `pos_id` FOREIGN KEY (`pos_id`) REFERENCES `worker_db_831321`.`attachment_position` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
> > ```
> 
> 竟然用到外键了，笑哭... 这个我得抽空研究下，暂时还没法快速更新。
> 
> 这个 mysqldiff 工具，也是我们游戏项目发版本时，诞生的，还有些功能不完善，敬请谅解！

哈哈。大佬威武。这个工具很6b。很多人都需要。这个搞好了。出去择业走路都带风 ，
还有丢失其他数据得情况
源：
```sql
CREATE TABLE `worker_db_831321`.`asset_category`  (
  `id` int(11) NOT NULL,
  `name` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `order_no` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;
```

目标：
```sql
CREATE TABLE `test1`.`asset_category`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `order_no` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '资产分类' ROW_FORMAT = Dynamic;
```

丢失：
 ```sql
AUTO_INCREMENT，COMMENT = '资产分类'
```

**Comment by lianhuazi** [comment]
go 不会。不能加入到一起。。python 学一点。但是这个对比原理不清楚。

**Comment by camry** [comment]
@lianhuazi 已发布 v3.0.7 版本，支持外键对比。要支持注释的对比需要加 --comment 参数。AUTO_INCREMENT 这个自动递增值的对比，个人感觉没啥用，所以没有支持。
