### ISSUE TITLE
 表名不同的结构不能对比吗

### ISSUE THREAD

**Issue by lizhiyou88** [camry/go-mysqldiff#8]
这个工具不能比对 表名不同的结构对比吗？
如果有参数db.table 就好了，希望表名不能 手动指定命名就行对比

**Comment by camry** [comment]
你这属于个性定制化需求了，正常业务场景，不可能有你说的这种情况哦。

**Comment by lizhiyou88** [comment]
会有这个需求的，比如有一个老系统，测试环境使用了老系统了表，但是表名更改了，并修改了字段，现在需要对比测试环境的表结构和老系统表结构的的差异了，官方的mysqldiff 可以对比不同的表名，有db1.object1:db2.object1参数，但是它这个对比索引不同时，联合索引顺序生成有错误。

**Comment by camry** [comment]
您这边可以 Fork 之后，实现这种需求。目前不会支持，感谢理解哈。

**Comment by lizhiyou88** [comment]
好吧 ，主要不会写go，如果可以表级别的对比，就很强的了，就像datagrip，对比表一样
